services:
  app:
    build: .
    env_file:
      - ./.env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: |
      sh -c "gunicorn --bind 0.0.0.0:8000 run:app"
    depends_on:
      - db

  db:
    image: postgres:17
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_NAME=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

volumes:
  postgres_data:
